### ISSUE TITLE
Fix colors for light mode

### ISSUE THREAD

**Issue by oxr463** [aad-for-linux/aad-for-linux#30]
The header and nav seem to have reverted to indigo instead of using our custom blue.

**Comment by outzhu** [comment]
![image](https://user-images.githubusercontent.com/89468347/190700591-13a46110-31cd-488b-b2be-04995c4e375b.png)
Indigo is kind of purple, right?
This looks blue to me.

**Comment by oxr463** [comment]
Yeah, but like a reddish blue almost purple: https://www.merriam-webster.com/dictionary/indigo. That color comes from the default theme.

It should be this color instead: https://www.webfx.com/web-design/random-color-picker/#0089d6
